micronaut:
  application:
    name: userService
  server:
    cors:
      enabled: true
      configurations:
        default:
          allowed-origins:
            - http://localhost:3000
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
          allowed-headers:
            - Content-Type
            - Authorization

datasources:
  default:
    url: jdbc:mysql://localhost:3306/employeeworkreport
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql : true
    entity-scan:
      packages: "com.employeeWorkReport.entity"

flyway:
  datasources:
    default:
      enabled: true

netty:
  default:
    allocator:
      max-order: 3
